### ISSUE TITLE
Uncaught ReferenceError: define is not defined

### ISSUE THREAD

**Issue by Lauxb** [zouyaoji/vue-supermap-cesium#1]
![image](https://user-images.githubusercontent.com/13530931/43934424-e192c252-9c81-11e8-95c1-dc46fbb7f73d.png)

**Comment by zouyaoji** [comment]
哈喽，这是因为超图的包没考虑NPM上造轮子，他们用的requirejs的方式引入的，他的意思是如果没有引入Workers/zlib.min就引入这个Workers/zlib.min。如果没有requirejs就报这个错了，其实不影响使用，如果确实觉得碍眼，你可以手动把./Cesium/zlib.min.js中“define("Workers/zlib.min", function () {})”删了。
